### ISSUE TITLE
Priority as string

### ISSUE THREAD

**Issue by fa93hws** [buildkite/terraform-provider-buildkite#219]
At the moment `priority` accepts number only. However, in fact, it should support string for environmental variable interpolation such as
```
- priority: "${STEP_PRIORITY:-0}"
```

**Comment by jradtilbrook** [comment]
Hi @fa93hws, I'm not sure where this fits into the terraform provider. We don't have any configuration for priority. Can you provide a more complete example of this issue for us to look at?

**Comment by fa93hws** [comment]
Hi thanks for the quick reply. I can not provide a CI link because it's internal sorry. What I have done is
```
  # language=yaml
  steps = <<YAML
env:
  ${local.env}
steps:
  - xxxx
    label: "xxxx"
    priority: $${STEP_PRIORITY_KICKSTART:-0}
    agents:
      - "xxxx"
```
And then I got the following error during apply saying:

> Error: One of the steps you provided was invalid: is not a number

This error vanish once I change `priority: $${STEP_PRIORITY_KICKSTART:-0}` to `priority: 1`
